"""
SofaScore ratings data for player-match combinations.
This module contains hardcoded SofaScore ratings for specific matches.
"""

import pandas as pd


SOFASCORE_RATINGS = {
    1953632: [
        ("N. Smith", 6.5),
        ("Mikael", 7.2),
        ("N. Paull", 7.4),
        ("H. Steele", 6.5),
        ("B. Kaltack", 7.6),
        ("D. Peraić-Cullen", 6.4),
        ("T. Sainsbury", 6.6),
        ("A. McCalmont", 6.5),
        ("S. Roux", 6.3),
        ("B. Brandtman", 6.5),
        ("A. Kuol", 6.8),
        ("Y. Cohen", 6.7),
        ("C. Talbot", 6.7),
        ("N. Atkinson", 6.8),
        ("Z. Schreiber", 6.9),
        ("K. Trewin", 7.1),
        ("P. Beach", 7.1),
        ("S. Souprayen", 7.4),
        ("S. Ugarković", 7.3),
        ("H. Politidis", 6.4),
        ("A. Behich", 7.1),
        ("M. Memeti", 6.5),
        ("Christian Theohaorous", 6.9),
        ("William Wilson", 6.7),
        ("Diesel Herrington", 7.2),
        ("Haine Eames", 6.3),
        ("Benjamin Mazzeo", 6.6),
        ("Germán Ferreyra", 7.0),
        ("Kavian Rahmani", 6.6),
        ("Michael Ghossaini", 6.5),
    ],
    2013725: [
        ("B. Garuccio", 7.5),
        ("R. Danzaki", 7.0),
        ("N. Botic", 6.4),
        ("D. Leonard", 7.1),
        ("A. Thurgate", 7.3),
        ("M. Sutton", 7.3),
        ("J. Donachie", 7.5),
        ("R. Bozinovski", 6.5),
        ("M. Ruhs", 6.2),
        ("T. Imai", 6.6),
        ("M. Grimaldi", 7.3),
        ("J. Kucharski", 6.9),
        ("R. Grant", 6.9),
        ("A. Popovic", 7.3),
        ("W. Kamijo", 7.2),
        ("D. Costa", 6.9),
        ("H. Devenish-Meares", 6.8),
        ("J. King", 6.9),
        ("A. Caceres", 6.8),
        ("J. Courtney-Perkins", 6.7),
        ("A. Segecic", 6.8),
        ("J. Lolley", 6.9),
        ("Oliver Lavale", 6.9),
        ("Abel Walatee", 6.2),
        ("Jordan Lauton", 6.7),
        ("Charbel Shamoon", 6.7),
        ("Kyle Reilly Shaw", 6.8),
        ("Anas Ouahim", 7.1),
        ("Tiago Quintal", 6.9),
    ],
    1886347: [
        ("F. D. Vries", 8.4),
        ("L. Gillion", 7.8),
        ("F. Gallegos", 7.6),
        ("N. Pijnaker", 7.7),
        ("A. Paulsen", 7.5),
        ("D. Hall", 7.1),
        ("L. Verstraete", 7.4),
        ("C. Elliot", 7.5),
        ("J. Brimmer", 7.3),
        ("G. May", 6.8),
        ("B. Gibson", 6.5),
        ("L. Rogerson", 6.3),
        ("E. Adams", 7.0),
        ("D. Ingham", 6.2),
        ("K. Grozos", 6.9),
        ("P. Čančar", 7.0),
        ("R. Scott", 6.9),
        ("A. Šušnjar", 6.8),
        ("C. Timmins", 6.5),
        ("T. K. Aquilina", 6.6),
        ("M. Natta", 6.8),
        ("L. Bayliss", 6.7),
        ("Neyder Moreno", 7.1),
        ("Max Mata", 6.7),
        ("Tommy Smith", 6.6),
        ("Daniel Wilmering", 6.4),
        ("Clayton Taylor", 6.8),
        ("Matthew Scarcella", 6.4),
        ("Justin Vidic", 6.5),
    ],
    2015213: [
        ("B. Garuccio", 7.7),
        ("M. Grimaldi", 6.3),
        ("N. Botic", 8.6),
        ("A. Thurgate", 7.4),
        ("D. Leonard", 6.6),
        ("M. Sutton", 5.6),
        ("J. Donachie", 6.7),
        ("R. Bozinovski", 6.4),
        ("M. Ruhs", 7.1),
        ("T. Imai", 6.6),
        ("R. Danzaki", 6.9),
        ("L. Rogerson", 6.2),
        ("H. Sakai", 6.5),
        ("M. Mata", 6.8),
        ("L. Verstraete", 6.4),
        ("D. Hall", 6.6),
        ("A. Paulsen", 6.5),
        ("F. Gallegos", 6.5),
        ("N. Pijnaker", 6.6),
        ("M. Francois", 5.9),
        ("F. D. Vries", 6.3),
        ("Jordan Lauton", 6.6),
        ("Abel Walatee", 6.4),
        ("Oliver Lavale", 7.0),
        ("Charbel Shamoon", 6.5),
        ("Ramy Najjarine", 7.3),
        ("Callan Elliot", 6.4),
        ("Neyder Moreno", 7.9),
        ("Jake Brimmer", 6.9),
        ("Jesse Randall", 7.3),
        ("Tommy Smith", 6.6),
    ],
    1899585: [
        ("F. D. Vries", 7.0),
        ("L. Gillion", 6.5),
        ("N. Pijnaker", 7.6),
        ("F. Gallegos", 7.7),
        ("J. Brimmer", 7.6),
        ("A. Paulsen", 7.2),
        ("D. Hall", 7.0),
        ("L. Verstraete", 6.7),
        ("G. May", 6.8),
        ("H. Sakai", 8.2),
        ("L. Rogerson", 6.6),
        ("T. Payne", 6.6),
        ("M. Sheridan", 6.7),
        ("P. Retre", 6.6),
        ("I. Hughes", 6.3),
        ("J. Oluwayemi", 6.6),
        ("K. Barbarouses", 7.4),
        ("K. Nagasawa", 6.6),
        ("S. Wootton", 7.2),
        ("A. Rufer", 7.7),
        ("H. Ishige", 6.8),
        ("S. Sutton", 7.0),
        ("Cameron Howieson", 7.5),
        ("Neyder Moreno", 6.6),
        ("Luis Toomey", 6.3),
        ("Tommy Smith", 6.2),
        ("Stefan Colakovski", 6.5),
        ("Marco Rojas", 6.5),
        ("Oskar van Hattum", 6.6),
    ],
    1925299: [
        ("A. Burke-Gilroy", 7.4),
        ("K. Jelacic", 7.3),
        ("J. O'Shea", 6.7),
        ("B. Warland", 6.8),
        ("M. Freke", 7.8),
        ("L. Herrington", 6.8),
        ("W. Shour", 7.4),
        ("H. V. D. Saag", 7.2),
        ("F. Berenguer", 7.4),
        ("T. Waddingham", 6.7),
        ("A. Zimarino", 6.5),
        ("T. Ostler", 6.5),
        ("J. Risdon", 7.3),
        ("D. Williams", 7.5),
        ("T. Gomulka", 7.1),
        ("A. Lebib", 7.1),
        ("C. Cook", 7.3),
        ("N. Pennington", 7.2),
        ("T. Mrčela", 7.1),
        ("A. Bugarija", 6.9),
        ("A. Faisal", 7.0),
        ("R. Warland", 6.8),
        ("Hosine Bility", 7.1),
        ("Jack Hingert", 6.4),
        ("Quinn MacNicol", 6.6),
        ("Jacob Brazete", 7.3),
        ("Neicer Acosta", 7.1),
        ("Jarrod Carluccio", 6.8),
        ("Khoa Ngo", 6.5),
        ("Nathaniel Blair", 6.3),
        ("Joel Anasmo", 6.4),
    ],
    2006229: [
        ("A. Behich", 7.5),
        ("K. Rahmani", 7.3),
        ("S. Souprayen", 7.0),
        ("K. Trewin", 7.1),
        ("P. Beach", 7.0),
        ("G. Ferreyra", 7.2),
        ("M. Leckie", 7.2),
        ("A. Kuen", 7.1),
        ("M. Caputo", 8.0),
        ("N. Atkinson", 7.5),
        ("M. Tillio", 7.0),
        ("S. Khaoui", 6.9),
        ("K. Adamson", 6.8),
        ("T. Uskok", 6.2),
        ("J. Hollman", 6.2),
        ("C. Ikonomidis", 6.3),
        ("K. Boli", 6.7),
        ("F. Kurto", 6.4),
        ("L. Brattan", 6.6),
        ("M. Jakoliš", 6.5),
        ("I. Vujica", 6.8),
        ("M. Jurman", 6.8),
        ("Harry Politidis", 7.0),
        ("Yonatan Cohen", 6.8),
        ("Steven Ugarković", 6.5),
        ("Lawrence Wong", 6.5),
        ("Michael Ghossaini", 6.6),
        ("Liam Rose", 6.8),
        ("Dean Bosnjak", 6.4),
        ("Harrison Sawyer", 6.6),
        ("Peter Makrillos", 6.2),
        ("Yianni Nicolaou", 6.5),
    ],
    2011166: [
        ("S. Sutton", 6.7),
        ("M. Sheridan", 6.6),
        ("H. Ishige", 6.2),
        ("S. Wootton", 7.2),
        ("J. Oluwayemi", 7.3),
        ("A. Rufer", 6.9),
        ("I. Hughes", 6.3),
        ("K. Nagasawa", 6.6),
        ("C. Piper", 7.5),
        ("T. Payne", 6.5),
        ("D. Arzani", 7.6),
        ("R. Teague", 6.8),
        ("R. Miranda", 6.9),
        ("M. Langerak", 6.4),
        ("J. Lachlan", 6.6),
        ("J. Valadon", 6.9),
        ("N. Velupillay", 8.2),
        ("K. Bos", 7.2),
        ("Z. Machach", 8.6),
        ("N. Vergos", 7.3),
        ("Paulo Retre", 7.3),
        ("Lukas Kelly-Heald", 6.8),
        ("Luke Brooke-Smith", 6.5),
        ("Nathan Walker", 6.7),
        ("Fin Conchie", 6.6),
        ("Reno Piscopo", 6.8),
        ("Brendan Hamill", 6.4),
        ("Alexander Badolato", 6.8),
        ("Fabian Monge", 6.4),
        ("Bruno Fornaroli", 6.4),
    ],
    2017461: [
        ("K. Bos", 6.7),
        ("N. Velupillay", 5.8),
        ("J. Valadon", 6.7),
        ("J. Lachlan", 6.8),
        ("J. Duncan", 6.5),
        ("B. Hamill", 6.9),
        ("R. Teague", 7.0),
        ("J. Inserra", 6.6),
        ("Z. Machach", 6.8),
        ("N. Vergos", 6.8),
        ("D. Arzani", 7.0),
        ("G. May", 6.8),
        ("L. Rogerson", 7.8),
        ("L. Verstraete", 7.6),
        ("D. Hall", 7.7),
        ("A. Paulsen", 6.6),
        ("N. Pijnaker", 7.6),
        ("H. Sakai", 7.7),
        ("J. Randall", 7.1),
        ("M. Francois", 7.0),
        ("F. Gallegos", 6.9),
        ("F. D. Vries", 7.7),
        ("Joshua Rawlins", 6.5),
        ("Bruno Fornaroli", 6.5),
        ("Clarismario", 6.5),
        ("Reno Piscopo", 6.6),
        ("Alexander Badolato", 6.7),
        ("Liam Gillion", 6.5),
        ("Neyder Moreno", 6.5),
        ("Tommy Smith", 6.6),
        ("Callan Elliot", 6.5),
        ("Jake Brimmer", 6.8),
    ],
    1996435: [
        ("J. Courtney-Perkins", 6.7),
        ("K. R. Shaw", 6.9),
        ("H. Devenish-Meares", 7.3),
        ("R. Grant", 6.9),
        ("Z. d. Jesus", 6.7),
        ("L. Sena", 8.2),
        ("A. Caceres", 7.8),
        ("C. Hollman", 6.8),
        ("J. Lolley", 8.6),
        ("A. Ouahim", 7.2),
        ("P. Klimala", 8.2),
        ("Adrian Segecic", 7.9),
        ("Jaiden Kucharski", 7.0),
        ("Douglas Costa", 6.7),
        ("D. Pierias", 7.9),
        ("Z. Clough", 7.1),
        ("J. Barnett", 6.7),
        ("B. Vriends", 6.1),
        ("E. Cox", 5.9),
        ("P. Kikianis", 8.0),
        ("E. Alagich", 6.8),
        ("J. Yull", 6.3),
        ("F. Talladira", 6.1),
        ("S. Mauk", 6.5),
        ("A. Goodwin", 6.7),
        ("Isaías", 6.6),
        ("Luka Jovanovic", 6.1),
        ("Yaya Dukuly", 6.4),
        ("Ryan White", 6.6),
        ("Austin Ayoubi", 6.8),
    ],
}


def load_sofascore_data() -> pd.DataFrame:
    """
    Load SofaScore ratings into a DataFrame.

    Returns:
        pd.DataFrame: DataFrame with columns [match_id, player_name, sofascore_rating]
    """
    rows = []
    for match_id, entries in SOFASCORE_RATINGS.items():
        for player_name, score in entries:
            if score is None:
                continue
            rows.append({
                "match_id": int(match_id),
                "player_name": str(player_name),
                "sofascore_rating": score,
            })

    df = pd.DataFrame(rows)
    df["sofascore_rating"] = pd.to_numeric(df["sofascore_rating"], errors="coerce")
    df = df.dropna(subset=["sofascore_rating"])
    df = df.sort_values(["match_id", "player_name"]).reset_index(drop=True)
    return df
